# Generated by Django 4.2.16 on 2026-01-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_service_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='duration_minutes',
            field=models.IntegerField(blank=True),
        ),
    ]
