# Generated by Django 4.2.16 on 2026-01-12 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_servicetype_duration_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(help_text='e.g. cash, esewa, khalti, stripe', max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0, help_text='Extra charge for this payment method', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customer_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='haircut_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='makeup_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='manicure_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='nailextension_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='pedicure_type',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='skincare_type',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.paymentmethod'),
        ),
    ]
