# Generated by Django 4.2.16 on 2026-01-12 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_paymentmethod_remove_appointment_customer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='staff',
            field=models.ForeignKey(blank=True, help_text='Staff assigned to this appointment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='booking.staff'),
        ),
    ]
