# Generated by Django 4.2.16 on 2026-01-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_appointment_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(help_text='Selected services for this appointment', related_name='appointments', to='booking.servicetype'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
